import type {FastifyPluginAsync} from "fastify";
import { requireAuth, requireTeamMember } from "../../common/middleware/auth.js";
import { listDailyReportsSchema } from "./schema.js";
const routes:FastifyPluginAsync=async(app)=>{
app.get('/daily-reports',{preHandler:[requireAuth],schema:listDailyReportsSchema},async(req:any,reply)=>{const {teamId,workDate}=req.query;const me=req.user.sub;const m=await app.prisma.teamMember.findUnique({where:{teamId_userId:{teamId,userId:me}},select:{id:true}});if(!m) return reply.status(403).send({code:'FORBIDDEN'});const where:any={teamId};if(workDate){const d=new Date(workDate);const next=new Date(d);next.setUTCDate(d.getUTCDate()+1);where.workDate={gte:d,lt:next};}const reports=await app.prisma.dailyReport.findMany({where,include:{entries:true,user:{select:{userId:true,name:true}}}});return {reports};});
app.get('/daily-reports/me',{preHandler:[requireAuth],schema:listDailyReportsSchema},async(req:any)=>{const {teamId,workDate}=req.query;const d=workDate?new Date(workDate):new Date();d.setUTCHours(0,0,0,0);const report=await app.prisma.dailyReport.findUnique({where:{teamId_userId_workDate:{teamId,userId:req.user.sub,workDate:d}},include:{entries:true}});return {report};});
app.post('/daily-reports',{preHandler:[requireAuth,requireTeamMember(app,(r:any)=>r.body?.teamId??'')]},async(req:any)=>{const b=req.body;const d=new Date(b.workDate);d.setUTCHours(0,0,0,0);const report=await app.prisma.dailyReport.upsert({where:{teamId_userId_workDate:{teamId:b.teamId,userId:req.user.sub,workDate:d}},create:{teamId:b.teamId,userId:req.user.sub,workDate:d,summary:b.summary||null,issue:b.issue||null,plan:b.plan||null},update:{summary:b.summary??undefined,issue:b.issue??undefined,plan:b.plan??undefined}});return {report};});
app.patch('/daily-reports/:dailyReportId',{preHandler:[requireAuth]},async(req:any,reply)=>{const r=await app.prisma.dailyReport.findUnique({where:{dailyReportId:req.params.dailyReportId}});if(!r) return reply.status(404).send({code:'NOT_FOUND'});if(r.userId!==req.user.sub) return reply.status(403).send({code:'FORBIDDEN'});const b=req.body;const report=await app.prisma.dailyReport.update({where:{dailyReportId:r.dailyReportId},data:{summary:b.summary??undefined,issue:b.issue??undefined,plan:b.plan??undefined}});return {report};});
app.delete('/daily-reports/:dailyReportId',{preHandler:[requireAuth]},async(req:any,reply)=>{const r=await app.prisma.dailyReport.findUnique({where:{dailyReportId:req.params.dailyReportId}});if(!r) return reply.status(404).send({code:'NOT_FOUND'});if(r.userId!==req.user.sub) return reply.status(403).send({code:'FORBIDDEN'});await app.prisma.dailyReport.delete({where:{dailyReportId:r.dailyReportId}});return {ok:true};});
app.post('/daily-reports/:dailyReportId/entries',{preHandler:[requireAuth]},async(req:any,reply)=>{const r=await app.prisma.dailyReport.findUnique({where:{dailyReportId:req.params.dailyReportId}});if(!r) return reply.status(404).send({code:'NOT_FOUND'});if(r.userId!==req.user.sub) return reply.status(403).send({code:'FORBIDDEN'});const b=req.body;const e=await app.prisma.dailyReportEntry.create({data:{dailyReportId:r.dailyReportId,taskId:b.taskId||null,startTime:new Date(b.startTime),endTime:b.endTime?new Date(b.endTime):null,title:b.title,content:b.content||null,minutes:b.minutes??0}});return {entry:e};});
app.patch('/daily-report-entries/:entryId',{preHandler:[requireAuth]},async(req:any,reply)=>{const e=await app.prisma.dailyReportEntry.findUnique({where:{entryId:req.params.entryId},include:{dailyReport:true}});if(!e) return reply.status(404).send({code:'NOT_FOUND'});if(e.dailyReport.userId!==req.user.sub) return reply.status(403).send({code:'FORBIDDEN'});const b=req.body;const data:any={}; if(b.taskId!==undefined) data.taskId=b.taskId||null; if(b.startTime!==undefined) data.startTime=new Date(b.startTime); if(b.endTime!==undefined) data.endTime=b.endTime?new Date(b.endTime):null; if(b.title!==undefined) data.title=b.title; if(b.content!==undefined) data.content=b.content||null; if(b.minutes!==undefined) data.minutes=b.minutes; const entry=await app.prisma.dailyReportEntry.update({where:{entryId:e.entryId},data});return {entry};});
app.delete('/daily-report-entries/:entryId',{preHandler:[requireAuth]},async(req:any,reply)=>{const e=await app.prisma.dailyReportEntry.findUnique({where:{entryId:req.params.entryId},include:{dailyReport:true}});if(!e) return reply.status(404).send({code:'NOT_FOUND'});if(e.dailyReport.userId!==req.user.sub) return reply.status(403).send({code:'FORBIDDEN'});await app.prisma.dailyReportEntry.delete({where:{entryId:e.entryId}});return {ok:true};});
};
export default routes;
