import type {FastifyPluginAsync} from "fastify";
import { requireAuth, requireTeamMember } from "../../common/middleware/auth.js";
import { createTaskSchema, listTasksSchema, updateTaskSchema } from "./schema.js";
const taskRoutes:FastifyPluginAsync=async(app)=>{
 app.get('/tasks',{preHandler:[requireAuth],schema:listTasksSchema},async(req:any,reply)=>{const {teamId,projectId}=req.query;const me=req.user.sub as string;const member=await app.prisma.teamMember.findUnique({where:{teamId_userId:{teamId,userId:me}},select:{id:true}});if(!member) return reply.status(403).send({code:'FORBIDDEN'});const items=await app.prisma.task.findMany({where:{teamId,...(projectId?{projectId}:{})},include:{project:{select:{projectId:true,name:true}}},orderBy:{createdAt:'desc'}});return {items};});
 app.get('/gantt',{preHandler:[requireAuth],schema:listTasksSchema},async(req:any,reply)=>{const {teamId,projectId}=req.query;const me=req.user.sub as string;const member=await app.prisma.teamMember.findUnique({where:{teamId_userId:{teamId,userId:me}},select:{id:true}});if(!member) return reply.status(403).send({code:'FORBIDDEN'});const items=await app.prisma.task.findMany({where:{teamId,...(projectId?{projectId}:{})},include:{project:{select:{name:true}}},orderBy:{createdAt:'asc'}});return {items:items.map((t:any)=>({...t,projectName:t.project?.name??null}))};});
 app.post('/tasks',{preHandler:[requireAuth,requireTeamMember(app,(r:any)=>r.body?.teamId??'')],schema:createTaskSchema},async(req:any)=>{const b=req.body;const task=await app.prisma.task.create({data:{teamId:b.teamId,projectId:b.projectId||null,title:b.title,description:b.description||null,startDate:b.startDate?new Date(b.startDate):null,endDate:b.endDate?new Date(b.endDate):null,progress:Number.isInteger(b.progress)?b.progress:0,parentTaskId:b.parentTaskId||null,createdByUserId:req.user.sub}});return {task};});
 app.patch('/tasks/:taskId',{preHandler:[requireAuth],schema:updateTaskSchema},async(req:any,reply)=>{const t=await app.prisma.task.findUnique({where:{taskId:req.params.taskId},select:{teamId:true}});if(!t) return reply.status(404).send({code:'TASK_NOT_FOUND'});const me=req.user.sub as string;const member=await app.prisma.teamMember.findUnique({where:{teamId_userId:{teamId:t.teamId,userId:me}},select:{id:true}});if(!member) return reply.status(403).send({code:'FORBIDDEN'});const b=req.body;const task=await app.prisma.task.update({where:{taskId:req.params.taskId},data:{...(b.title!==undefined?{title:b.title}:{}),...(b.description!==undefined?{description:b.description||null}:{}),...(b.startDate!==undefined?{startDate:b.startDate?new Date(b.startDate):null}:{}),...(b.endDate!==undefined?{endDate:b.endDate?new Date(b.endDate):null}:{}),...(b.progress!==undefined?{progress:b.progress}:{}),...(b.parentTaskId!==undefined?{parentTaskId:b.parentTaskId||null}:{})}});return {task};});
 app.delete('/tasks/:taskId',{preHandler:[requireAuth]},async(req:any,reply)=>{const t=await app.prisma.task.findUnique({where:{taskId:req.params.taskId},select:{teamId:true}});if(!t) return reply.status(404).send({code:'TASK_NOT_FOUND'});const member=await app.prisma.teamMember.findUnique({where:{teamId_userId:{teamId:t.teamId,userId:req.user.sub}},select:{id:true}});if(!member) return reply.status(403).send({code:'FORBIDDEN'});await app.prisma.task.delete({where:{taskId:req.params.taskId}});return {ok:true};});
};
export default taskRoutes;
